# -*- coding: utf-8 -*-
"""PythonAML01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWAm2ChLOOrXX1wOuspti1NFeGbcMUr-
"""

! ls

print("Python for AML")

number1 = 20

number1

number2 = 20.02

number2

n = (1+3j) #complex number

n

# string
name = "amirhossein"

name

type(number1)

type(number2)

type(n)

type(name)

number1 = "python"

type(number1)

# a-z A-Z 0-9 _
_name = "amir"

_name

a = 20
b = 30

temp = a 
a = b
b = temp
print(a,b)

x = 200
y = -100
z = 150
x, y, z = y, x, 25
print(x,y,z)

#print 

print("python for aml")

print("x: ", x)

# https://pyformat.info/
print("x: {}, y: {}, z: {}".format(x, y, z))

str1 = "amir"
str2 = "hossein"

str1 + str2

str1 * 10

15 * str2

# > >= < <= != ==
3 > 5

6 < 100

5 == 5

-100 == x

-100 == y

# and / or / not ?
True and True

True and False

True or False

p = (-100 == y) and (-100 == x)
p

not(p)

a = 20
print(a)

#input

f = float(input())
print(type(f))
print(f*10)

xnumber = 200
xstr = str(xnumber)
type(xstr)

xnumber = 200
xnumber = str(xnumber)
type(xnumber)

yy = 32
print(yy)
print(type(yy))
yy = float(yy)
print(yy)
print(type(yy))

qqq = 25 - 4j
print(2*qqq)

print(qqq*qqq)

print("Enter a number : ", end="\n")
number = int(input())

number = int(input("Enter a number : "))

# if - else - elif
x = False
if (x):
  print("5555")

if(not(x)):
  print("2222")

x = False

if (x):
  print("5555")

else:
  print("2222")

num = int(input("Enter a number : "))
if (num >= 0):
  print("+++++++")
else:
  print("-------")

num = int(input("Enter a number : "))
if (num >= 0):
  if(num == 0):
    print("0000000")
  else:
    print("+++++++")
else:
  print("-------")

num = int(input("Enter a number : "))
if (num > 0):
  print("+++++++")
elif (num == 0):
  print("0000000")
else:
  print("-------")

g = int(input("number : "))
# g % 2 ==> 0 : zoj / g % 2 ==> 1 : fard
if (g%2 == 0):
  print("Zooooj")
  #print("22222")
else:
  print("Fard")

# float , avg a , b , khoda behet rahm kone
havij = float(input("Enter your average: "))
if havij >= 17:
  print("AAAAAA")
elif (havij >=12):
  print("BBBBBB")
else:
  print("Khoda rahm kkone behet")

# Loop 
print("AUT")
print("AUT")
print("AUT")
print("AUT")
print("AUT")
print("AUT")
print("AUT")
print("AUT")
print("AUT")
print("AUT")

number = 1
while (number <=10):
  #print(number, " AUT")
  print("{}. AUT".format(number))
  number = number + 1

a = int(input("a : "))
b = int(input("b : "))
if a>b:
  a, b = b, a
while(a<=b):
  print(a)
  a = a + 1 # a += 1

a = int(input("a : "))
b = int(input("b : "))
if a>b:
  a, b = b, a

if a % 2 == 0: # 0 ==> 1 : zooj 
  a = a+1

while(a<= b):
  print(a)
  a += 2

# f(x,y) = x^2 + y^2 + 1
def fxy(x, y):
  if x>y:
    return 1
  else:
    return (x**2)+(y**2)+1

fxy(2,3)

bbbbbbb = fxy(3,2)

bbbbbbb

num = int(input("Enter a number : "))
if (num > 0):
  print("+++++++")
elif (num == 0):
  print("0000000")
else:
  print("-------")

def n_p_0(nplsd):
  if (nplsd > 0):
    return 1
  elif (nplsd == 0):
    return 0
  else:
    return -1

n_p_0(25)

def n_p_0_2(nplsd):
  if (nplsd > 0):
    return "PPPPPPPPP"
  elif (nplsd == 0):
    return "ZERO"
  else:
    return "NNNNNNN"

n_p_0_2(25)

def printAML(p1, p2, t):
  if t == '+':
    print("{} + {} = {}".format(p1, p2, p1+p2))
  elif t == "-":
    print("{} - {} = {}".format(p1, p2, p1-p2))
  else:
    print("Wrong type...")

printAML(2, 25, '+')

a = 96
b = 102
x = '-'
printAML(a, b, x)

a = 80
b = 60
TYPE = '-'
printAML(t=TYPE, p1=a, p2=b)

