# -*- coding: utf-8 -*-
"""Video25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19QBv6qlnqMyV-qfp2HYTn1dB4d4ME9ip
"""

import numpy as np

a = np.array([1,2,3,4,5,6])
print(type(a))

print(a.shape)

list1 = [5,6,-1,3]

list1[2]

a[2]

list1[3]=25

list1

a[2] = -3

a

b = np.array([[1,2,3,-1,5],
              [4,5,6,-2,5],
              [7,8,9,-3,5],
              [0,3,5,-4,5]])
b.shape

l2 = [[1,2,3,-1,5],
      [4,5,6,-2,5],
              [7,8,9,-3,5],
              [0,3,5,-4,5]]

l2

l2[1][4] = -100

l2

b[1, 4]

b[1, 4] = -3.14

b

c = np.array([3.14,2,1])

c

a = -3.14

type(a)

a = int(-3.14)
# a = int(a)

type(a)

a

a = np.zeros((3,5),dtype=int) #default = float 
print(a)

a[2,4] = 12.5

a

b = np.ones((10,2))

b

b[8,1] = -1

b

c = np.full((3,4), 25, dtype = float)

c

x = 5
sh = (5,7)
y = np.full(sh, x)

y

type(sh)

e = np.eye(5) #I

e

m = (3,4)
r = np.random.random(m)

r

r2 = np.random.randint(low = 8, high = 12, size=5)

r2

type(r2)

r2.shape

type(r)

print(r.dtype)

print(r2.dtype)

#add
x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)

x

y

x.dtype

y.dtype

print(x+y)

c = np.add(x,y)

c

c.dtype

print(x-y)

s = np.subtract(x,y)

s

print(x*y)

m = np.multiply(x,y)

m

m.dtype

print(x/y)

d = np.divide(x,y)
d

sq = np.sqrt(x)
sq

rsqrt = np.sqrt(r2)
rsqrt

a = np.array([1, 3, -5] )
b = np.array([4, -2, -1])

np.dot(a,b)

a.dot(b)

x

y

x.dot(y)

x

np.sum(x)

bb = a*b

bb

np.sum(bb)

a.dot(b)

x

print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

x

