# -*- coding: utf-8 -*-
"""Video10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vg2lUr9nHENEL-nntTBbQEwbBN_CGr9D
"""

#Tuple
t = ()

t8 = tuple()
type(t8)

mt = (2, 3.14, "ahb", False)

mt

mt[0]

mt.index('ahb')

mt[2]

mt.count("ahb")

# Dictionary key-value
d = {}

type(d)

d = dict()

di = {
    1:"yek",
    "1":"yek ch",
    "2":"do",
    "3":"se"
}

di

di['1']

di[1]

di[4]="chahar"

di

#di[25]
print(di.get("ali",False))

di = {
    "1":"yek ch",
    "2":"do",
    "3":"se"
}

x = input("kilid ra vared konid : ")
if di.get(x, False):
  print(di[x])
else:
  di[x]=input("value ra vared kon : ")
  print("ezafe shod...")
  print(di)

