# -*- coding: utf-8 -*-
"""Video08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A97DqJqk8juKXdiO8XaAedQGFu_lVzzN
"""

number = int(input("please enter a number : "))
if number > 0:
  print("mosbat")
if number < 0:
  print("manfi")

number = int(input("please enter a number : "))
if number > 0:
  print("mosbat")
if number < 0:
  print("manfi")
if number == 0:
  print("zero (sefr)")

number = int(input("please enter a number : "))
if number >= 0:
  print("mosbat ya sefr")
else:
  print("manfi")

avg = float(input("moadel khodet r VARED KON :"))
if avg < 0 or avg > 20 :
  print("moshkel darad.")
else:
  if avg>=0 and avg<10:
    print("oftade")
  else:
    if avg >=10 and avg < 12:
      print("mashroot")

avg = float(input("moadel khodet r VARED KON :"))
if avg < 0 or avg > 20 :
  print("moshkel darad.")
elif avg>=0 and avg<10:
  print("oftade")
elif avg>=10 and avg<12:
  print("mashroot")
elif avg>=12 and avg<17:
  print("B")
else:
  print("A")

17.25