# -*- coding: utf-8 -*-
"""Video21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10taCGROpaFlKGSVtRldMmsho50xeQPZ2
"""

!pip install parsivar

from tqdm import tqdm

x = 0
for i in tqdm(range(20000000)):
    x +=1

print(x)

import parsivar

from parsivar import stemmer

xxx = stemmer()