# -*- coding: utf-8 -*-
"""Video13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_fLUTgBVfhOey-49415sOcicR3UTApxD
"""

if (1):
  print("---if---")

while (1):
  print("---while---")



number = 1
while(number <= 10):
  print(number, end = " ")
  number = number + 1

num1 = int(input("adad 1 ra vared kon :"))
num2 = int(input("adad 2 ra vared kon :"))
while(num1<=num2):
  print(num1, end =" ")
  num1 = num1 + 1

# zooj beine 2 adad
num1 = int(input("adad 1 ra vared kon :"))
num2 = int(input("adad 2 ra vared kon :"))
if num1 % 2 == 1:
  num1 = num1+1

while(num1<=num2):
  print(num1, end =" ")
  num1 = num1 + 2

number = 1
while(number <= 10):
  print(number, end = " ")
  number = number + 1
  if number==5:
    continue

num1 = int(input("adad 1 ra vared kon :"))
num2 = int(input("adad 2 ra vared kon :"))
while(num1<=num2):
  print(num1, end =" ")
  num1 = num1 + 1
else:
  print("tamam shod....")

