# -*- coding: utf-8 -*-
"""OS02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--zFkiJz62fFLNU5AmwQYa1Qj14ezf5P
"""

x = int(input("adad 1 ra vared kon :"))
y = int(input("adad 2 ra vared kon :"))
ch = input("amalgar ra vared kon :")
if ch == "+":
  print(x+y)
elif ch == "*":
  print(x*y)
elif ch == "-":
  print(x-y)
else:
  print("amalgar vared shode namotabar ast.")

# with Dictionary 
x = int(input("adad 1 ra vared kon :"))
y = int(input("adad 2 ra vared kon :"))
ch = input("amalgar ra vared kon :")
d = {
    "+":x+y,
    "-":x-y,
    "*":x*y
}
if d.get(ch,False):
  print(d[ch])
else:
  print("amalgar eshtebah")

