# -*- coding: utf-8 -*-
"""Python_Video39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zNe_u90vN7o-lE7hk5djFeD2GC5q-Mlh
"""

!pip install parsivar

import numpy as np

np.power(2,3)

np.power(542,22)

np.power(-32,3)

np.power(0.25,0.1)

x = int(input("adad ra vared konid: "))
if x > 0:
  print(np.power(x,2))
elif x==0:
  print(np.power(x,3))
else:
  print(np.power(x,4))

np.power(20,0)

x = int(input("adad ra vared konid: "))
while(x>-6):
  print(x)
  x = x-1

x = int(input("adad1 ra vared konid: "))
y = int(input("adad2 ra vared konid: "))
if x%2 == 1:
  x = x+1
for i in range(x,y,2):
  print(i, end=" ")

