# -*- coding: utf-8 -*-
"""Video24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JDTKy6tFC2itf2Tz7FHsdLQEGu3NFGmA
"""

import time
import numpy as np

num = 10000000 # dah milion

num

a = list(range(num))

b = list(reversed(range(num)))

c= list()

for i in range(num):
  c.append(a[i]+b[i])

c[0]

c[2]

c[12548]

c = []

c[99999999]

st = time.time()
for i in range(num):
  c.append(a[i]+b[i])
et = time.time()
print(et-st)

ap = np.array(list(range(num)))
bp = np.array(list(reversed(range(num))))

ap[10]

ap[0]

ap[9999999]

bp[0]

stp = time.time()
c = np.add(ap, bp)
etp = time.time()
print(etp-stp)

print((et-st)/(etp-stp))

