# -*- coding: utf-8 -*-
"""Video15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S3KcdIaxbZ5XQnk2rdjArFcMD48tmtr_
"""

lis = [1,2,3,4]
len(lis)

s = "amirhossein"
len(s)

#for
esmha = ["ali", 'hasan', 'taghi', 'reza']
for esm in esmha:
  print(esm)

esmha[2]

for i in range(20,1,-2):
  print(i)

# esmha 
for i in range(len(esmha)):
  print(esmha[i])
  esmha[i]= esmha[i].upper()
esmha

for ch in "amirhossein babaeayan az hamedan":
  if ch == " ":
    continue
  print(ch)

num = int(input("tedad vorodi ha ra : "))
sum = 0
sumy = 0
for i in range(num):
  print("==========",i+1,"=========")
  x = int(input("nomre : "))
  y = int(input("zarib : "))
  sum = x*y + sum
  sumy = y+ sumy
print(sum/sumy)

l = [1,5,9,-1,3]
sum = 0
for item in l:
  sum = sum + item
print("avg = ",sum/len(l))
print("sum = ", sum)

l = [1,5,9,-1,3]
sum = 0
for i in range(len(l)):
  sum = sum +l[i] 
print("avg = ",sum/len(l))
print("sum = ", sum)

l = [1,5,9,-1,3]
sum = 0
for item in l:
  item = 2

l

l = [1,5,9,-1,3]
sum = 0
for i in range(len(l)):
  l[i] = 5

l

