# -*- coding: utf-8 -*-
"""Video07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11eIqSaLDtMH9f0E1kjOBOPVhG8-sTrXP
"""

print("Salam Donya !!!")

print("Salam Donya !!!", 2+3)

print("yek adad vared kon :")
_havij = input()
print(_havij)

_akbar2 = input("yek adad vared kon :")
print(_akbar2)

x = input("ye chizi vared kon : ")
print(type(x))

y = input("yek adad vared kon : ")
print(2*y)

y = input("yek adad vared kon : ")
print('2'+y)

z = input("yek adad vared kon : ")
z = int(z)
print(z+10)

z = int(input("yek adad vared kon : "))
print(z+10)

# p = 2*pi*r , s= pi * r^2
r = float(input("shoa ra vared kon : "))
pi = 3.14
print("mohit barabar ast ba : ", 2*pi*r)
print("masahat barabar ast ba : ", pi*(r**2))

#swap
a = 20
b = 30
print(a,b)

t = a
a = b
b = t
print(a,b)

x = -10
y = 25
print(x,y)
x , y = y , x
print(x,y)

