# -*- coding: utf-8 -*-
"""Video17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wwtoAK6FOlUJGqllsKix3CHigVRJCwDg
"""

#function 
'''
def name(input1, input2, ...):
  ----
  ----
  ----
  return output1,out2,...
'''
print("Function")

#power 

x = int(input("paye :"))
y = int(input("tavan : "))
p = 1
for i in range(y):
  p=p*x
print(x, "^", y, "=", p)

def power(paye, tavan):
  o = 1
  for i in range(tavan):
    o = o * paye
  return o

power(2,3)

power(3,4)

power(4,4)

power(1,2)

x = 2
y = 3
power(x,y)

x = int(input("paye :"))
y = int(input("tavan : "))
r = power(x,y)
print(type(r))
print(x,"^",y,"=",r)

def print_etelaat(name, age, ghad):
  print("name :", name, type(name))
  print("age :", age, type(age))
  print("ghad :", ghad, type(ghad))

print_etelaat("ali", 20, 179.6)

n = "amirhossein"
a = 24
g = 187.3
print_etelaat(n,a, g )

name = "amirhossein"
age = 24
ghad = 187.3
print_etelaat(name,age, ghad )

def powert(paye, tavan):
  o = 1
  x = 75
  for i in range(tavan):
    o = o * paye
  return o, x, o*7

x,y,z = powert(5,2)
print(x,y,z)

