# -*- coding: utf-8 -*-
"""Video09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qJjE78LKo__R8Cbry9dC52FJoJsrzfLg
"""

l = list()
l2 = []

type(l)

type(l2)

l3 = ["ahb", 2, 3.14, True]

print(l3)

l3

l3[1]

l3[2]

l3[4]

l3.append("alireza")

l3

l3[4]

l3.reverse()

l3

l3[4]

l3.remove(True)

l3

l3.append(False) #push

l3

l3.pop()

l3

l3.append("alireza")

l3

l3.count(2)

l4 = [1,2,0,5,-7,4] #
l4.sort()

l4

l5 = ["ahb","ali","zahra", "niloofar", "mohammad"]
l5.sort()

l5

