# -*- coding: utf-8 -*-
"""Video12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Niy-nviempFqf6hPB-BH9LBh9tWKfIER
"""

#str
a = "fagdjfsadbjas684123-=032839"
type(a)

a[6]

ac = a.capitalize()

ac

a.count(a[-2])

au = a.upper()

au

au.lower()

inp = input()

print(inp)

inpl = inp.split("-")

inpl

type(inpl)

inpl[-2]

inp = input()
inpl = inp.split("s")

inpl

type(inp)

